### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by zhangrf21** [AndreaAmicarelliRSE/SPHERA#12]
Hi, after compiling the program, how do I run the example files?

**Comment by GiordanoAgateRSE** [comment]
Hi zhangrf21,
in all tutorials there is a “.inp” file that collects all the commands contained in the “/input” folder. 
To launch the tutorial case from the command line, just name the executable followed by the name of the case (.inp file without extensions): Ex.: ExecutableFile.x InputFileName 
If you use queues you must create the script file with the keywords that must be those allowed by the queue manager to define the name of the job, the queue, the cores, the node etc. 
If you use the OpenMP version you must set the number of cores (processes) that you want to use for parallel execution. Ex.; export OMP_NUM_THREADS=64
Giordano

**Comment by zhangrf21** [comment]
need to run each .inp file in the “/input” folder in turn？

**Comment by GiordanoAgateRSE** [comment]
No, in the /input/template folder there are commented templates of input file subdivided in different sections.
For each tutorial there is the /input folder with all the input sections and input files with the correct case name in the filename.
The chapter 9 and the par. 11.15 of the file SPHERA_v_10_0_0_documentation_file.pdf explain how to use input files. 
Alternatively you can copy all files of the sections in a single file named casename.inp.
Than you can execute the code
Giordano

**Comment by zhangrf21** [comment]
When I run “ExecutableFile.x InputFileName”，the error is reported as follows：
cat: './input/*/*.inp': No such file or directory
 >> Diagnostic  5 detected * Run ended unsuccessfully

**Comment by GiordanoAgateRSE** [comment]
You must be in the case folder (for example one of the tutorials) and the InputFileName must be the case name of the tutorial
